# Generated by Django 5.0.2 on 2024-09-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=150)),
                ("status", models.CharField(max_length=10)),
                ("duedate", models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
